services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings
    command: >
      sh -c "uv run python manage.py migrate &&
             uv run python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

volumes:
  sqlite_data: