# Generated by Django 5.2.5 on 2025-08-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Enter the task description', max_length=64, verbose_name='Text')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Enter the task priority', verbose_name='Priority')),
                ('completed', models.BooleanField(default=False, help_text='Check if the task is completed', verbose_name='Completed')),
                ('project', models.ForeignKey(help_text='Select the project', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-priority'],
            },
        ),
    ]
