# Generated by Django 5.2.5 on 2025-08-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
